name: Terminus Site Inventory

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/15 * * * *'
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}

      - name: Process sites and owners
        env:
          PANTHEON_ORGANIZATION_ID: ${{ secrets.PANTHEON_ORGANIZATION_ID }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          MAIL_RECIPIENT: ${{ secrets.MAIL_RECIPIENT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        run: |
          php scripts/sites.php
